[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "1.0.2"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/hakuturu583/simple_lanelet2"
homepage = "https://github.com/hakuturu583/simple_lanelet2"
rust-version = "1.85"

[workspace.dependencies]
ll2-core = { path = "crates/ll2-core" }
ll2-matching = { path = "crates/ll2-matching" }
ll2-io = { path = "crates/ll2-io" }
ll2-projection = { path = "crates/ll2-projection" }
ll2-routing = { path = "crates/ll2-routing" }
ll2-traffic-rules = { path = "crates/ll2-traffic-rules" }

parking_lot = "0.12"
rstar = "0.13"
quick-xml = "0.41"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
