[package]
name = "ll2-traffic-rules"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Traffic rules for a Lanelet2-compatible library"

[dependencies]
ll2-core.workspace = true
