"""Type stubs for ``lanelet2``.

Generated by ``tools/gen_stubs.py``. Do not edit by hand.
"""

from . import core as core
from . import geometry as geometry
from . import io as io
from . import matching as matching
from . import projection as projection
from . import routing as routing
from . import traffic_rules as traffic_rules

BUG_COMPAT: bool
__all__ = [
    "core",
    "geometry",
    "io",
    "matching",
    "projection",
    "routing",
    "traffic_rules",
]
