"""Type stubs for ``lanelet2.io``.

Generated by ``tools/gen_stubs.py`` from the built extension. Do not edit by hand.
"""

from typing import Any


class Origin:
    """`lanelet2.io.Origin`."""
    def __init__(self, /, *args, **kwargs) -> Any: ...
    position: Any

def load(filename, projector=None) -> Any: ...
def loadRobust(filename, projector) -> Any: ...
def write(filename, map, projector=None, params=None) -> Any: ...
def writeRobust(filename, map, projector=None, params=None) -> Any: ...
