"""Type stubs for ``lanelet2.matching``.

Generated by ``tools/gen_stubs.py`` from the built extension. Do not edit by hand.
"""

from typing import Any


class ConstLaneletMatch:
    """`lanelet2.matching.ConstLaneletMatch`."""
    def __init__(self, /, *args, **kwargs) -> Any: ...
    distance: Any
    lanelet: Any

class ConstLaneletMatchProbabilistic:
    """`lanelet2.matching.ConstLaneletMatchProbabilistic`."""
    def __init__(self, /, *args, **kwargs) -> Any: ...
    distance: Any
    lanelet: Any
    mahalanobisDistSq: Any

class Object2d:
    """`lanelet2.matching.Object2d`."""
    def __init__(self, /, *args, **kwargs) -> Any: ...
    absoluteHull: Any
    objectId: Any
    pose: Any

class ObjectWithCovariance2d(Object2d):
    """`lanelet2.matching.ObjectWithCovariance2d`."""
    def __init__(self, /, *args, **kwargs) -> Any: ...
    absoluteHull: Any
    objectId: Any
    pose: Any
    positionCovariance: Any
    vonMisesKappa: Any

class Pose2d:
    """`lanelet2.matching.Pose2d`."""
    def __init__(self, /, *args, **kwargs) -> Any: ...

class PositionCovariance2d:
    """`lanelet2.matching.PositionCovariance2d`."""
    def __init__(self, /, *args, **kwargs) -> Any: ...

def getDeterministicMatches(map, obj, maxDist) -> Any: ...
def getProbabilisticMatches(map, obj, maxDist) -> Any: ...
def removeNonRuleCompliantMatches(matches, trafficRules) -> Any: ...
