"""Type stubs for ``lanelet2.traffic_rules``.

Generated by ``tools/gen_stubs.py`` from the built extension. Do not edit by hand.
"""

from typing import Any


class Locations:
    """`lanelet2.traffic_rules.Locations`."""
    Germany: Any
    def __init__(self, /, *args, **kwargs) -> Any: ...

class Participants:
    """`lanelet2.traffic_rules.Participants`."""
    Bicycle: Any
    Pedestrian: Any
    Train: Any
    Vehicle: Any
    VehicleBus: Any
    VehicleCar: Any
    VehicleCarCombustion: Any
    VehicleCarElectric: Any
    VehicleEmergency: Any
    VehicleMotorcycle: Any
    VehicleTaxi: Any
    VehicleTruck: Any
    def __init__(self, /, *args, **kwargs) -> Any: ...

class SpeedLimitInformation:
    """`lanelet2.traffic_rules.SpeedLimitInformation`."""
    def __init__(self, /, *args, **kwargs) -> Any: ...
    isMandatory: Any
    speedLimit: Any
    speedLimitKmH: Any
    speedLimitMPS: Any

class TrafficRules:
    """`lanelet2.traffic_rules.TrafficRules`."""
    def __init__(self, /, *args, **kwargs) -> Any: ...
    def canChangeLane(self, from_, /, to) -> Any: ...
    def canPass(self, lanelet, other=None) -> Any: ...
    def hasDynamicRules(self, lanelet) -> Any: ...
    def isOneWay(self, lanelet) -> Any: ...
    def laneChangeType(self, boundary, virtualIsPassable=False) -> Any: ...
    def location(self) -> Any: ...
    def participant(self) -> Any: ...
    def speedLimit(self, lanelet) -> Any: ...

def create(location, participant) -> Any: ...
