#!/usr/bin/env python3
"""Generates type stubs from the built extension.

Generated from the implementation rather than copied from upstream: the stubs
Lanelet2 ships disagree with its own bindings in a dozen places -- properties that
are really methods, constructors that do not exist, wrong item types. Deriving them
from what is actually there keeps them honest.

Signatures come from each callable's ``__text_signature__`` where PyO3 provides
one, and fall back to ``(*args, **kwargs)`` where it does not.
"""

import inspect
import pathlib
import sys

import lanelet2

SUBMODULES = ["core", "geometry", "io", "matching", "projection", "routing", "traffic_rules"]

HEADER = '''"""Type stubs for ``lanelet2.{name}``.

Generated by ``tools/gen_stubs.py`` from the built extension. Do not edit by hand.
"""

from typing import Any

'''


def signature_of(obj, drop_self=False):
    text = getattr(obj, "__text_signature__", None)
    if not text:
        return "(*args: Any, **kwargs: Any)"
    if drop_self and text.startswith("($self, "):
        text = "(self, " + text[len("($self, "):]
    elif drop_self and text == "($self)":
        text = "(self)"
    elif drop_self and text.startswith("($self"):
        text = "(self" + text[len("($self"):]
    return text.replace("$self", "self").replace("$module, ", "").replace("$module", "")


def emit_class(name, cls, out):
    bases = [base.__name__ for base in cls.__bases__ if base.__name__ != "object"]
    out.append("class {}{}:".format(name, "({})".format(", ".join(bases)) if bases else ""))
    doc = inspect.getdoc(cls)
    if doc:
        out.append('    """{}"""'.format(doc.splitlines()[0]))

    members = [n for n in dir(cls) if not n.startswith("_") or n in ("__init__", "__len__",
                                                                     "__getitem__", "__iter__")]
    wrote = False
    for member_name in sorted(members):
        member = inspect.getattr_static(cls, member_name, None)
        if isinstance(member, property):
            out.append("    @property")
            out.append("    def {}(self) -> Any: ...".format(member_name))
            wrote = True
        elif callable(member):
            out.append("    def {}{} -> Any: ...".format(member_name, signature_of(member, True)))
            wrote = True
        elif member is not None and not inspect.isclass(member):
            out.append("    {}: Any".format(member_name))
            wrote = True
    if not wrote and not doc:
        out.append("    ...")
    out.append("")


def main():
    target = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "python/lanelet2")
    for name in SUBMODULES:
        module = getattr(lanelet2, name)
        out = [HEADER.format(name=name)]
        public = [n for n in dir(module) if not n.startswith("_")]

        for attribute in sorted(public):
            value = getattr(module, attribute)
            if inspect.isclass(value):
                emit_class(attribute, value, out)
        for attribute in sorted(public):
            value = getattr(module, attribute)
            if inspect.isclass(value):
                continue
            if callable(value):
                out.append("def {}{} -> Any: ...".format(attribute, signature_of(value)))
            else:
                out.append("{}: Any".format(attribute))
        out.append("")
        (target / "{}.pyi".format(name)).write_text("\n".join(out))
        print("wrote", target / "{}.pyi".format(name))

    (target / "__init__.pyi").write_text(
        '"""Type stubs for ``lanelet2``.\n\n'
        "Generated by ``tools/gen_stubs.py``. Do not edit by hand.\n"
        '"""\n\n'
        "from . import core as core\n"
        "from . import geometry as geometry\n"
        "from . import io as io\n"
        "from . import matching as matching\n"
        "from . import projection as projection\n"
        "from . import routing as routing\n"
        "from . import traffic_rules as traffic_rules\n\n"
        "BUG_COMPAT: bool\n"
        "__all__ = [\n"
        '    "core",\n    "geometry",\n    "io",\n    "matching",\n'
        '    "projection",\n    "routing",\n    "traffic_rules",\n]\n'
    )
    print("wrote", target / "__init__.pyi")


if __name__ == "__main__":
    main()
