#!/usr/bin/env python3
"""Generates type stubs from the built extension.

Generated from the implementation rather than copied from upstream: the stubs
Lanelet2 ships disagree with its own bindings in a dozen places -- properties that
are really methods, constructors that do not exist, wrong item types. Deriving them
from what is actually there keeps them honest.

Signatures come from each callable's ``__text_signature__`` where PyO3 provides
one, and fall back to ``(*args, **kwargs)`` where it does not.
"""

import ast
import inspect
import keyword
import pathlib
import sys

import lanelet2

SUBMODULES = ["core", "geometry", "io", "matching", "projection", "routing", "traffic_rules"]

#: The Autoware extension's own package, whose submodules are ordinary Python rather
#: than native ones. Importing `regulatory_elements` is what registers its subtypes,
#: so the generator has to import it before anything else reports what it exposes.
EXTENSION = "autoware_lanelet2_extension_python"
EXTENSION_SUBMODULES = [
    "regulatory_elements",
    "projection",
    "utility.query",
    "utility.utilities",
]

HEADER = '''"""Type stubs for ``lanelet2.{name}``.

Generated by ``tools/gen_stubs.py`` from the built extension. Do not edit by hand.
"""

from typing import Any

'''


def split_parameters(text):
    """Split the body of a ``__text_signature__`` on its top-level commas.

    Defaults are arbitrary source, so a naive ``text.split(",")`` breaks on
    anything like ``sep=(1, 2)`` or ``byteorder=','``.
    """
    parts, current, depth, quote = [], [], 0, None
    for char in text:
        if quote is not None:
            current.append(char)
            if char == quote:
                quote = None
            continue
        if char in "\"'":
            quote = char
        elif char in "([{":
            depth += 1
        elif char in ")]}":
            depth -= 1
        elif char == "," and depth == 0:
            parts.append("".join(current).strip())
            current = []
            continue
        current.append(char)
    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return parts


def parameter_name(parameter):
    return parameter.split("=", 1)[0].split(":", 1)[0].strip().lstrip("*")


def rename_keyword_parameters(parameters):
    """Rename parameters that are Python keywords, e.g. ``canChangeLane(self, from, to)``.

    A native binding can name a parameter ``from``; a stub that repeats the name
    verbatim is not parseable, and one unparseable stub aborts the whole mypy
    run for anything that imports us. Such a parameter can never be passed by
    keyword from Python anyway, so it is renamed and everything up to it is
    marked positional-only -- valid syntax, and a closer description of what the
    binding actually accepts. A signature that already carries a ``/`` is left
    to say for itself where the positional-only group ends.
    """
    renamed, out = -1, []
    for index, parameter in enumerate(parameters):
        name = parameter_name(parameter)
        if keyword.iskeyword(name):
            parameter = parameter.replace(name, name + "_", 1)
            renamed = index
        out.append(parameter)
    if renamed >= 0 and "/" not in out:
        out.insert(renamed + 1, "/")
    return out


def signature_of(obj):
    text = getattr(obj, "__text_signature__", None)
    if not text:
        return "(*args: Any, **kwargs: Any)"
    parameters = []
    for parameter in split_parameters(text[1:-1]):
        if parameter == "$module":
            continue
        if parameter == "$self":
            parameter = "self"
        elif parameter == "$type":
            # Argument Clinic marks a classmethod's class parameter `$type`, the
            # way it marks a method's instance parameter `$self`. It reaches us
            # through `int.from_bytes`, inherited by the enum classes.
            parameter = "cls"
        parameters.append(parameter)
    return "({})".format(", ".join(rename_keyword_parameters(parameters)))


def emit_class(name, cls, out):
    bases = [base.__name__ for base in cls.__bases__ if base.__name__ != "object"]
    out.append("class {}{}:".format(name, "({})".format(", ".join(bases)) if bases else ""))
    doc = inspect.getdoc(cls)
    if doc:
        out.append('    """{}"""'.format(doc.splitlines()[0]))

    members = [n for n in dir(cls) if not n.startswith("_") or n in ("__init__", "__len__",
                                                                     "__getitem__", "__iter__")]
    wrote = False
    for member_name in sorted(members):
        member = inspect.getattr_static(cls, member_name, None)
        if isinstance(member, property):
            out.append("    @property")
            out.append("    def {}(self) -> Any: ...".format(member_name))
            wrote = True
        elif callable(member):
            out.append("    def {}{} -> Any: ...".format(member_name, signature_of(member)))
            wrote = True
        elif member is not None and not inspect.isclass(member):
            out.append("    {}: Any".format(member_name))
            wrote = True
    if not wrote and not doc:
        out.append("    ...")
    out.append("")


def stub_module(module, name, target, filename):
    out = [HEADER.format(name=name)]
    public = [n for n in dir(module) if not n.startswith("_")]

    for attribute in sorted(public):
        value = getattr(module, attribute)
        if inspect.isclass(value):
            emit_class(attribute, value, out)
    for attribute in sorted(public):
        value = getattr(module, attribute)
        if inspect.isclass(value) or inspect.ismodule(value):
            continue
        if callable(value):
            out.append("def {}{} -> Any: ...".format(attribute, signature_of(value)))
        else:
            out.append("{}: Any".format(attribute))
    out.append("")
    path = target / filename
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(out)
    # Signature text is not guaranteed to be valid Python, and mypy treats an
    # unparseable stub as fatal -- one bad line stops the type-check run of every
    # project that imports us. Refuse to write one rather than ship it.
    try:
        ast.parse(text)
    except SyntaxError as error:
        line = text.splitlines()[error.lineno - 1] if error.lineno else ""
        raise SystemExit(
            "{}: generated stub does not parse at line {}: {}\n    {}".format(
                path, error.lineno, error.msg, line.strip()
            )
        )
    path.write_text(text, encoding="utf-8")
    print("wrote", path)


def main():
    target = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "python/lanelet2")
    for name in SUBMODULES:
        stub_module(getattr(lanelet2, name), name, target, "{}.pyi".format(name))

    (target / "__init__.pyi").write_text(
        '"""Type stubs for ``lanelet2``.\n\n'
        "Generated by ``tools/gen_stubs.py``. Do not edit by hand.\n"
        '"""\n\n'
        "from . import core as core\n"
        "from . import geometry as geometry\n"
        "from . import io as io\n"
        "from . import matching as matching\n"
        "from . import projection as projection\n"
        "from . import routing as routing\n"
        "from . import traffic_rules as traffic_rules\n\n"
        "BUG_COMPAT: bool\n"
        "__all__ = [\n"
        '    "core",\n    "geometry",\n    "io",\n    "matching",\n'
        '    "projection",\n    "routing",\n    "traffic_rules",\n]\n'
    )
    print("wrote", target / "__init__.pyi")


def main_extension():
    """Stubs for the Autoware extension package, if it is present."""
    import importlib

    root = pathlib.Path("python") / EXTENSION
    if not root.exists():
        return
    # Importing this registers the extension's subtypes, which is what makes the
    # regulatory-element classes reachable at all.
    importlib.import_module("%s.regulatory_elements" % EXTENSION)
    for name in EXTENSION_SUBMODULES:
        module = importlib.import_module("%s.%s" % (EXTENSION, name))
        stub_module(module, name, root, "%s.pyi" % name.replace(".", "/"))


if __name__ == "__main__":
    main()
    main_extension()
